name: 'Beanstalk Deploy'
description: 'Deploy a zip file to AWS Elastic Beanstalk'
author: 'Einar Egilsson'
runs:
  using: 'node12'
  main: 'beanstalk-deploy.js'
inputs:
  aws-access-key:
    description: 'AWS Access Key'
    required: true
  aws-secret-key:
    description: 'AWS Secret Key'
    required: true
  aws-session-token:
    description: 'AWS Session Token when using temporary security credentials such as when assuming a role in AWS through STS'
    required: false  
  region:
    description: 'AWS Region'
    required: true
  application-name:
    description: 'Beanstalk application name'
    required: true
  environment-name:
    description: 'Beanstalk environment name. If empty a version will be created but not deployed anywhere.'
    required: false
  version-label:
    description: 'Version label for new Beanstalk version'
    required: true
  version-description:
    description: 'Version description for the new Beanstalk version'
    required: false
  deployment-package:
    description: 'Zip file with the version to deploy. If skipped the action will deploy existing version.'
    required: false
  use-existing-version-if-available:
    description: 'If set to "true" then the action will deploy an existing version with the given version_label if it already exists, but otherwise create the version and deploy it.'
    required: false
  wait-for-deployment:
    description: 'Whether the action should wait for the deployment to finish and log status messages during the wait. Default is "true". If set to "false" the action will start the deployment on Beanstalk and then exit.'
    required: false
  wait-for-environment-recovery:
    description: 'How many seconds to wait for the environment to return to Green state after deployment is finished. Default is 30 seconds.'
    required: false

branding:
  icon: 'arrow-up'  
  color: 'green'
